# Matrix and Vectors : ML - Andrew Ng.

In [12]:
# initialize matrix A and B ---------------- Here I'm using python

In [13]:
A = [[1, 2, 4], 
    [5, 3, 2]]

B = [[1, 3, 4],
    [1, 1, 1]]

In [15]:
result = [[0, 0, 0],       
         [0, 0, 0]]

for i in range(len(A)):
    for j in range(len(A[0])):
        result[i][j] = A[i][j] + B[i][j]            # Addition of two matrix formulae.

for r in result:
    print(r)

[2, 5, 8]
[6, 4, 3]


In [16]:
# Substraction A - B 

In [17]:
for i in range(len(A)):
    for j in range(len(A[0])):
        result[i][j] = A[i][j] - B[i][j]            # Addition of two matrix formulae.

for r in result:
    print(r)

[0, -1, 0]
[4, 2, 1]


In [18]:
# Multiplication A * B : 

In [31]:
import numpy as np

In [33]:
A = [[1, 2, 4], 
    [5, 3, 2]]

B = [[1, 3, 4],
    [1, 1, 1]]

result = [[0, 0, 0], 
        [0, 0, 0]] 

In [35]:
for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]
for r in result:
    print(r)

[3, 5, 6]
[8, 18, 23]


In [37]:
# Program to multiply two matrices (vectorized implementation) 
# Program to multiply two matrices (vectorized implementation) 


import numpy as np 
# take a 3x3 matrix 
A = [[12, 7, 3], 
    [4, 5, 6], 
    [7, 8, 9]] 

# take a 3x4 matrix 
B = [[5, 8, 1, 2], 
    [6, 7, 3, 0], 
    [4, 5, 9, 1]] 

# result will be 3x4 

result= [[0,0,0,0], 
        [0,0,0,0], 
        [0,0,0,0]] 

result = np.dot(A,B) 

for r in result: 
    print(r) 


[114 160  60  27]
[74 97 73 14]
[119 157 112  23]
