# K - Nearest - Neighbors :
> K Nearest Neighbor algorithm falls under the Supervised Learning category and is used for classification (most commonly) and regression. It is a versatile algorithm also used for imputing missing values and resampling datasets. As the name (K Nearest Neighbor) suggests it considers K Nearest Neighbors (Data points) to predict the class or continuous value for the new Datapoint.

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('Social_Network_Ads.csv')
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
x = data.iloc[:, [2,3]].values
y = data.iloc[:,[-1]].values

### Train test split : 

In [4]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0)

### Scalling down values :

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

### KNN :

In [6]:
from sklearn.neighbors import KNeighborsClassifier
ks = KNeighborsClassifier(n_neighbors = 5)
ks.fit(x_train, y_train)

KNeighborsClassifier()

In [7]:
y_pred = ks.predict(x_test)

### Confusion Matrix and Score check :

In [8]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[55  3]
 [ 1 21]]


In [9]:
## Accuracy check 

y_pred = ks.predict(x_test)
ac = accuracy_score(y_test, y_pred)
print('Accuracy :', ac*100)

Accuracy : 95.0


In [10]:
x_test

array([[-7.98950822e-01,  4.94607583e-01],
       [-2.12648508e-02, -5.77359062e-01],
       [-3.12897090e-01,  1.46942725e-01],
       [-7.98950822e-01,  2.62831011e-01],
       [-3.12897090e-01, -5.77359062e-01],
       [-1.09058306e+00, -1.44652121e+00],
       [-7.01740076e-01, -1.59138156e+00],
       [-2.15686344e-01,  2.14601566e+00],
       [-1.96547978e+00, -5.58617754e-02],
       [ 8.53631867e-01, -7.80163563e-01],
       [-7.98950822e-01, -6.06331134e-01],
       [-9.93372315e-01, -4.32498705e-01],
       [-1.18475597e-01, -4.32498705e-01],
       [ 7.59458956e-02,  2.04886868e-01],
       [-1.77105829e+00,  4.65635512e-01],
       [-6.04529329e-01,  1.36376973e+00],
       [-1.18475597e-01,  2.04886868e-01],
       [-1.86826903e+00,  4.36663440e-01],
       [ 1.63131784e+00,  1.74040666e+00],
       [-3.12897090e-01, -1.38857706e+00],
       [-3.12897090e-01, -6.64275277e-01],
       [ 8.53631867e-01,  2.14601566e+00],
       [ 2.70367388e-01, -5.48386991e-01],
       [ 8.

In [11]:
ks.predict([[-1.09058306e+00, -1.44652121e+00]])

array([0], dtype=int64)

In [12]:
ks.predict([[-6.04529329e-01,  2.31984809e+00]])

array([1], dtype=int64)

In [13]:
ks.predict([[3.67578135e-01,  2.62831011e-01]])

array([0], dtype=int64)

### First age, then salary : outcome is wheather that person will buy or not !

> 1. 0 : means __NO__
> 2. 1 : Means __YES__