# Numpy 

In [3]:
# Single dimansional array.

In [2]:
import numpy as np

n1 = np.array([2, 3, 5, 6])
n1

array([2, 3, 5, 6])

In [5]:
# Multidimansional array

In [8]:
n2 = np.array([[20, 30, 50, 45], [66, 20, 12, 68], [33, 25, 45, 13]])
n2

array([[20, 30, 50, 45],
       [66, 20, 12, 68],
       [33, 25, 45, 13]])

In [ ]:
# initialize array with zeros : 

In [10]:
n3 = np.zeros([3,5])
n3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
# Initialize numpy array with the same number : 

In [12]:
n4 = np.full((2,4),10)
n4

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

# Initialize numpy array within a perticular range : 

In [13]:
# arange() methode

In [14]:
import numpy as np

In [15]:
n7 = np.arange(10,20)
n7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
n8 = np.arange(10,50,5)
n8

array([10, 15, 20, 25, 30, 35, 40, 45])